services:
  db:
    image: mariadb
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      TZ: CET
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1

  phpmyadmin:
    image: beeyev/phpmyadmin-lightweight
    restart: unless-stopped
    ports:
      - 9002:80
    environment:
      PMA_USER: root