name: CI

on:
  push:
    branches: [ "main", "dev" ]
    paths: [ ".github/workflows/ci.yml", "Src/**", "Tools/**", "NationsConverter.sln" ]
  pull_request:
    branches: [ "main", "dev" ]
    paths: [ ".github/workflows/ci.yml", "Src/**", "Tools/**", "NationsConverter.sln" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          8.0.x
    - name: Restore dependencies
      run: dotnet restore NationsConverter.sln
    - name: Build
      run: dotnet build NationsConverter.sln -c Release --no-restore -p:ContinuousIntegrationBuild=true
    - name: Test
      run: dotnet test NationsConverter.sln --no-build --verbosity normal
